name: Backup to Backblaze B2

on:
  schedule:
    - cron: '0 */2 * * *'  # Alle 2 Stunden
  workflow_dispatch:        # Manuelle Ausführung bleibt erhalten

env:
  B2_BUCKET: ${{ secrets.B2_BUCKET_NAME }}
  B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
  B2_APP_KEY: ${{ secrets.B2_APP_KEY }}

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Debug Environment
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "B2 Bucket: $B2_BUCKET"
          echo "B2 Account ID exists: ${{ env.B2_ACCOUNT_ID != '' }}"
          echo "Current directory content:"
          ls -la
      
      - name: Prepare backup directory
        run: |
          find . -name ".git" -type d -exec rm -rf {} +
          find . -name ".github" -type d -exec rm -rf {} +
          find . -name "node_modules" -type d -exec rm -rf {} +
          find . -name "vendor" -type d -exec rm -rf {} +
      
      - name: Install b2 CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade b2
          b2 version
      
      - name: Authenticate with B2
        run: |
          echo "${{ env.B2_APP_KEY }}" | b2 authorize-account ${{ env.B2_ACCOUNT_ID }}
      
      - name: Remove existing backup files
        run: |
          echo "Debug: Showing b2 version and available commands"
          b2 version
          b2 --help
          
          echo "Checking for existing files..."
          echo "Listing files in backup directory..."
          b2 ls "${{ env.B2_BUCKET }}" "backups/" | while read -r line; do
            if [[ ! -z "$line" ]]; then
              echo "Processing line: $line"
              FILE_NAME=$(echo "$line" | awk '{print $1}')
              FILE_ID=$(echo "$line" | awk '{print $2}')
              echo "Deleting: $FILE_NAME (ID: $FILE_ID)"
              b2 delete-file-version "$FILE_NAME" "$FILE_ID" || true
            fi
          done

      - name: Upload files to B2
        run: |
          echo "Starting upload to bucket: ${{ env.B2_BUCKET }}"
          # Rekursives Hochladen aller Dateien
          for file in $(find . -type f); do
            if [[ $file != ./.* ]]; then  # Ignoriere versteckte Dateien/Ordner
              echo "Uploading: $file"
              b2 upload-file \
                "${{ env.B2_BUCKET }}" \
                "$file" \
                "backups/$file"
            fi
          done
          echo "Upload completed"