name: Backup to Backblaze B2

on:
  schedule:
    - cron: '0 */2 * * *'  # Alle 2 Stunden
  workflow_dispatch:

env:
  B2_BUCKET: ${{ secrets.B2_BUCKET_NAME }}
  B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
  B2_APP_KEY: ${{ secrets.B2_APP_KEY }}

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Debug Environment
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "B2 Bucket: $B2_BUCKET"
          echo "B2 Account ID exists: ${{ env.B2_ACCOUNT_ID != '' }}"
          echo "Current directory content:"
          ls -la

      - name: Prepare backup directory
        run: |
          find . -name ".git" -type d -exec rm -rf {} +
          find . -name ".github" -type d -exec rm -rf {} +
          find . -name "node_modules" -type d -exec rm -rf {} +
          find . -name "vendor" -type d -exec rm -rf {} +

      - name: Install B2 CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade b2
          b2 version

      - name: Authenticate with B2
        run: |
          echo "${{ env.B2_APP_KEY }}" | b2 account authorize ${{ env.B2_ACCOUNT_ID }}

      - name: Remove existing files in B2 bucket
        run: |
          echo "Removing existing files in 'scripts' directory..."
          b2 rm --recursive "b2://${{ env.B2_BUCKET }}/scripts/" || true

      - name: Exclude .env and .gitignore from upload
        run: |
          rm -f .env .gitignore

      - name: Upload files to B2
        run: |
          echo "Starting upload to bucket: ${{ env.B2_BUCKET }}"
          b2 sync --delete . "b2://${{ env.B2_BUCKET }}/scripts/"
          echo "Upload completed"